--- 
  locationsPath: ../../config/locations-bs.json
  tariffsPath: ../../config/tariffs.json
  # stage: "local"
  # ethProvider: "http://localhost:8545"
  # msp seed ending 'cool'; 
  # cpo seed ending 'warm'; 
  # driver seed ending 'cold';
  seed: "filter march urge naive sauce distance under copy payment slow just warm"
  gasPrice: 2
  tokenAddress: '0x945BBda7699ed93d37cfBc897310A4c33B739631'
